name: "post to bsky"

# on: push
on: 
    schedule:
            - cron: "26 11 15 4 *"

jobs:
    test-bot:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: npm ci
          - name: test-bot
            env:
              BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
              BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD}}
            run: npm test
    
    post-image:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - run: npm ci

          - name: post-image
            env:
              BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
              BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD}}
            run: npm start


                


               
