name: "post to bsky"

on: push

jobs:
    post-image:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: test
            env:
              BSKY_HANDLE: ${{ secrets.BSKY_IDENTIFIER }}
              BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD}}
            run: npx tsx src/index.ts


                


               
